SENTENCE_MODEL_NAME = 'stsb-roberta-large'
SEMANTIC_THRESHOLD = 0.75

N_GRAM_SIZE = 5
LEXICAL_THRESHOLD = 0.50

IMAGE_HASH_SIZE = 8
IMAGE_THRESHOLD = 5

CHUNK_SIZE_SENTENCES = 3
MAX_SEARCH_QUERIES = 10
